

JSON_FILE_PARAM = '-p='
JSON_FILE_DEFAULT = 'params.json'
COMMENT_PARAM = '-c='
LOG_FILE_NAME = 'main.log'

NUM_TILES = 9
NUM_TILES_L2_MIX = 4
FROM_X1 = 1
FROM_I1 = FROM_X1
FROM_X2 = 0
FROM_I2 = FROM_X2
NUM_CROPS = 3

SPECTRAL_NORM_UPDATE_OPS = "spectral_norm_update_ops"
